name: Lint and Format

on:
  push:
    branches:
      - master
      - amay/feature
  pull_request:
    branches:
      - main
      - "feature/*"
      - "bugfix/*"

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Adjust Node.js version if needed

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run ESLint
        run: |
          cd frontend
          npx eslint "src/**/*.{ts,tsx,js,jsx}"
