name: Prettier

on:
  push:
    branches:
      - shazia/feature
      - master
      - tahreem/docs
  pull_request:
    branches:
      - shazia/feature
      - master
      - tahreem/docs

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          npm install

      - name: Run Prettier check
        run: |
          npx prettier --check .

      - name: Run Prettier and format code
        if: ${{ failure() }}
        run: |
          npx prettier --write .
